"""empty message

Revision ID: 96926f85cbb1
Revises: 054fd6038ecc
Create Date: 2017-02-25 23:04:59.614681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96926f85cbb1'
down_revision = '054fd6038ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
